kind: Service
apiVersion: v1
metadata:
  name: weather-data-container
  labels:
    name: weather-data-container
spec:
  ports:
    - nodePort: 30163 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: weather-data-container
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: weather-data-container
spec:                
  selector:         
    matchLabels:
      app: weather-data-container
  replicas: 1        
  template:
    metadata:
      labels:        
        app: weather-data-container
    spec:
      containers:
        - name: weather-data-container
          image: weather-data-container
          ports:
            - containerPort: 8080                
          env:  
          - name: DB_HOST  
            valueFrom: 
              configMapKeyRef:
                name: db-conf 
                key: host
          - name: DB_NAME  
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME 
            valueFrom:
              secretKeyRef:
                name: db-credentials 
                key: username
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     
        